#!/bin/bash
set -veuo pipefail;

if ! hash pyenv 2>/dev/null; then
    echo "pyenv required." >2;
    echo "run 'curl https://pyenv.run | bash' or check out https://github.com/pyenv/pyenv" >2;
    exit 1
fi

# ensure required version of python is installed
pyenv install --skip-existing "$(pyenv local)";

PYTHON="$(pyenv which python)";
PIP="$(pyenv which pip)";

# ensure dependencies are installed
"$PIP" install -r requirements.txt;

BLACK="$(pyenv which black)";

# format our code
"$BLACK" .;

# run our code
"$PYTHON" main.py;
